apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sites-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - test1.daywer.ru
    - test2.daywer.ru
    secretName: sites-tls
  rules:
  - host: test1.daywer.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test1
            port:
              number: 80
  - host: test2.daywer.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test2
            port:
              number: 80
